### ISSUE TITLE
Tests are failing

### ISSUE THREAD

**Issue by mmautner** [gusdan/django-elasticache#12]
To reproduce:
```shell
$ git clone git@github.com:gusdan/django-elasticache.git
$ cd django-elasticache
$ pip install -e .
$ pip install nose mock
$ nosetests
E.........
======================================================================
ERROR: tests.test_backend.test_invalidate_cache
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/max/.virtualenvs/mysite/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/max/.virtualenvs/mysite/lib/python2.7/site-packages/mock/mock.py", line 1305, in patched
    return func(*args, **keywargs)
  File "/Users/max/code/django-elasticache/tests/test_backend.py", line 94, in test_invalidate_cache
    backend._local._client = None
AttributeError: 'ElastiCache' object has no attribute '_local'

----------------------------------------------------------------------
Ran 10 tests in 0.172s

FAILED (errors=1)
``` 

It might be related to not pinning the version of `pylibmc` in `setup.py`:

https://github.com/gusdan/django-elasticache/blob/master/setup.py#L18

**Comment by gusdan** [comment]
Good point. Problem was in django 1.7. Fixed in version 1.0.0
